---
- name: Config environment for IoT Core
  hosts: localhost
  gather_facts: true

  tasks:
    
    - name: Get current user
      shell: whoami
      register: current_user

    #- name: Create ggc_user
    #  user:
    #    name: ggc_user
    #    state: present
    
    #- name: Create ggc_group
    #  group:
    #    name: ggc_group
    #    state: present

      
    - name: Write to the file
      copy:
        dest: "facts.txt"
        content: |
          "{{ hostvars['localhost'] }}"


    #- name: Improve harlink/softlink security
    #  lineinfile:
    #    path: test.txt
    #    line: "{{ hostvars['localhost'] }}"

    # - name: Display OS type
    #   debug:
    #     msg: "{{ ansible_distribution }}"
